# =====================================================================
# NiO d-d nIXS — non-resonant inelastic X-ray scattering, S(q, ω)
# =====================================================================
#
# Builds the e^{i q·r} scattering operator with `nixs` (the plane-wave
# multipole expansion; the d→d channel admits ranks k ∈ {0,2,4}) and feeds
# it to `dynamical_structure_factor` for S(q, ω). nIXS is a *valence* d→d
# probe (no core hole), so it reaches the quadrupole (k=2) and hexadecapole
# (k=4) channels that are dipole-forbidden, and the spectrum is anisotropic:
# the multipole weights depend on the crystal direction of q.
#
# Model: the full NiO ligand-field multiplet (Ni 3d + ligand 3d-symmetry
# bath) — the same model as the L-edge XAS/RIXS examples, since nIXS leaves
# the 2p core untouched. Below T_N NiO orders antiferromagnetically with the
# Ni moment along a ⟨112⟩ easy axis; the exchange field along [112] orients
# the ³A₂g triplet, whose three partners are summed over.
#
# The radial Bessel moments Rj_k(q) = ⟨R_3d|j_k(qr)|R_3d⟩ are computed from
# the tabulated Ni 3d Hartree-Fock radial function (P(r)=r·R(r), reduced
# weight) → Rj0,Rj2,Rj4 ≈ 0.070, 0.161, 0.086 at q = 4.5/a₀ (k=2-dominant).
#
#   julia --project=. examples/08_nio_nixs.jl

using MOADyna
using DelimitedFiles

# ---------------------------------------------------------------------
# NiO ligand-field multiplet model (Ni 3d + ligand bath)
# ---------------------------------------------------------------------
m = ShellModel([:Ni_3d, :L_3d])

F2dd, F4dd      = 11.142, 6.874   # eV, d-d Slater integrals
zeta_3d         = 0.081           # eV, 3d atomic spin-orbit
tenDq, tenDqL   = 0.56, 1.44      # eV, cubic (Oh) crystal field on Ni / ligand
Veg, Vt2g       = 2.06, 1.21      # eV, Ni-ligand hybridisation (eg, t2g)
Udd, Delta      = 7.3, 4.7        # eV, Hubbard U_dd and charge-transfer Δ
Bz              = 1.0e-6          # tiny field to fix the quantisation axis
Hex             = 0.120           # eV, AFM exchange (molecular) field along [112]

# Charge-transfer on-site energies from the d⁸ / d⁹L̲ configuration anchors.
es = onsite_energies(m;
    shells  = (:Ni_3d, :L_3d),
    U       = (Ni_3d = Udd,),
    anchors = [(Ni_3d = 8, L_3d = 10) => 0.0,
               (Ni_3d = 9, L_3d = 9)  => Delta])

H = coulomb(m, :Ni_3d; U = Udd, F = (F2dd, F4dd)) +
    zeta_3d * LS(m, :Ni_3d) +
    tenDq   * Akm(m, :Ni_3d, :Oh, [0.6, -0.4]) +
    tenDqL  * Akm(m, :L_3d,  :Oh, [0.6, -0.4]) +
    Veg  * hop(m, :Ni_3d, :L_3d, :Oh; irrep = :Eg)  +
    Vt2g * hop(m, :Ni_3d, :L_3d, :Oh; irrep = :T2g) +
    Bz  * (2 * Sz(m, :Ni_3d) + Lz(m, :Ni_3d)) +
    Hex * (Sx(m, :Ni_3d) + Sy(m, :Ni_3d) + 2 * Sz(m, :Ni_3d)) / sqrt(6) +
    es.Ni_3d * n(m, :Ni_3d) + es.L_3d * n(m, :L_3d)

# 18 electrons shared between Ni 3d and the bath (d⁸ + d⁹L̲ + d¹⁰L̲²).
basis_gs = basis(m, nshells(m, :Ni_3d) + nshells(m, :L_3d) == 18)
H_sp = assemble(compile(H, basis_gs), basis_gs)
@info "NiO ligand-field basis" states = length(basis_gs)

gs = eigen(H_sp, basis_gs; n = 3)               # the three ³A₂g partners
@info "Ground triplet" E = round.(gs.values; digits = 6)

# ---------------------------------------------------------------------
# Radial Bessel moments Rj_k(q) from the Ni 3d Hartree-Fock radial function
# ---------------------------------------------------------------------
# P_3d(r) = r·R_3d(r). Prefer a live atomic Hartree-Fock (Cowan RCN) run via
# `radial_wavefunction`; fall back to the committed asset (the same data,
# generated by examples/gen_nio_radial.jl) when no Cowan binary is configured.
local rgrid, P3d
cowan = get(ENV, "MOADYNA_COWAN", get(ENV, "TTMULT", ""))
if !isempty(cowan) && isfile(cowan)
    rw    = radial_wavefunction(:Ni, "3d8"; cowan = cowan)
    rgrid = rw.r
    P3d   = copy(rw.P["3d"])
    @info "Radial function: live Cowan RCN run (radial_wavefunction)"
else
    radial_file = joinpath(pkgdir(MOADyna), "docs", "src", "assets", "nio", "Ni_3d_HF_radial.dat")
    M     = readdlm(radial_file, '\t'; skipstart = 1)   # column 7 ("3d") is P(r)=r·R(r)
    rgrid = Float64.(M[:, 1])
    P3d   = Float64.(M[:, 7])
    @info "Radial function: committed asset (set MOADYNA_COWAN to compute live)"
end
P3d ./= sqrt(radial_integral(P3d, P3d, rgrid, 0; kind = :power, weight = :reduced))

q  = 4.5                                          # momentum transfer (per a₀)
Rj = Dict(k => radial_integral(P3d, P3d, rgrid, k; kind = :bessel, q = q, weight = :reduced)
          for k in (0, 2, 4))
@info "Bessel radial moments Rj_k(q)" q Rj0 = round(Rj[0]; digits = 4) Rj2 = round(Rj[2]; digits = 4) Rj4 = round(Rj[4]; digits = 4)

# ---------------------------------------------------------------------
# S(q, ω) for four crystallographic directions of q (production resolution)
# ---------------------------------------------------------------------
qdirs = ["001" => (0.0,              0.0),
         "110" => (π / 2,            π / 4),
         "111" => (acos(sqrt(1/3)),  π / 4),
         "123" => (acos(sqrt(9/14)), acos(sqrt(1/5)))]

omega_grid = range(-0.5, 6.0; length = 1301)     # eV; k=0 elastic line sits at ω=0
Gamma      = 0.1                                  # Lorentzian FWHM (eV)

cols  = [collect(omega_grid)]
labels = String["omega"]
for dir in qdirs
    label = dir.first
    qtheta, qphi = dir.second
    T_q = nixs(m, :Ni_3d => :Ni_3d; theta = qtheta, phi = qphi, radial_integrals = Rj)
    S   = zeros(length(omega_grid))
    for i in 1:3                                   # sum over the three ³A₂g partners
        S .+= dynamical_structure_factor(H_sp, basis_gs, T_q;
                  omega_grid = omega_grid, Gamma = Gamma,
                  ψ₀ = gs.vectors[:, i], Eg = gs.values[i]).tensor
    end
    push!(cols, S); push!(labels, "S_q$(label)")
    # report d-d peak (exclude the elastic line below 0.5 eV)
    dd = [j for j in eachindex(omega_grid) if omega_grid[j] > 0.5]
    jpk = dd[argmax(S[dd])]
    @info "S(q,ω) d-d nIXS" qhat = label ω_peak = round(omega_grid[jpk]; digits = 3) peak = round(S[jpk]; digits = 5)
end

out = reduce(hcat, cols)
writedlm(joinpath(@__DIR__, "nio_nixs_dd.txt"), out)
@info "Done. S(q,ω) for [001],[110],[111],[123] written to nio_nixs_dd.txt (column order: $(join(labels, ", ")))."
