# =====================================================================
# Regenerate the NiO 3d Hartree–Fock radial asset from MOAD + Cowan RCN
# =====================================================================
#
# Produces docs/src/assets/nio/Ni_3d_HF_radial.dat — the tabulated
# Ni²⁺ 3d⁸ Hartree–Fock radial functions P_nl(r) = r·R_nl(r) used by the
# NiO nIXS tutorial to build the radial Bessel moments. The data is
# computed by MOAD's own `radial_wavefunction` (a live Cowan RCN run), so
# the tutorial depends on no external radial file.
#
# Requires a Cowan RCN binary: set ENV["MOAD_COWAN"] (or ENV["TTMULT"]) to
# its path, or edit `COWAN` below. Re-run after changing the configuration
# or the RCN build:
#
#   MOAD_COWAN=/path/to/rcnlanl julia --project=. examples/gen_nio_radial.jl
#
# Output format: tab-separated, one header line, columns
#   r  1s  2s  2p  3s  3p  3d        (r in Bohr; P_nl = r·R_nl, ∫P²dr = 1)
# matching the layout the tutorial reads (`readdlm(...; skipstart=1)`,
# column 1 = r, column 7 = 3d).

using MOAD

const COWAN = get(ENV, "MOAD_COWAN", get(ENV, "TTMULT", ""))
isempty(COWAN) && error("""
    gen_nio_radial: no Cowan binary. Set ENV["MOAD_COWAN"] (or ENV["TTMULT"])
    to an RCN binary path, e.g. rcnlanl.""")

# Ni²⁺ ground configuration (the nIXS valence shell is 3d).
rw = radial_wavefunction(:Ni, "3d8"; cowan = COWAN)

# Column order matches the committed asset.
const ORBITALS = ["1s", "2s", "2p", "3s", "3p", "3d"]
for o in ORBITALS
    haskey(rw.P, o) || error("gen_nio_radial: orbital $o missing from Cowan output")
end

outpath = joinpath(pkgdir(MOAD), "docs", "src", "assets", "nio", "Ni_3d_HF_radial.dat")
open(outpath, "w") do io
    # Provenance header (the tutorial skips this one line).
    println(io, "# Ni2+ 3d8 Hartree-Fock radial functions P_nl(r)=r*R_nl(r); " *
                "columns: r(Bohr) " * join(ORBITALS, " ") * "; " *
                "generated by MOAD.radial_wavefunction (Cowan RCN) via " *
                "examples/gen_nio_radial.jl")
    for (i, r) in enumerate(rw.r)
        print(io, r)
        for o in ORBITALS
            print(io, '\t', rw.P[o][i])
        end
        print(io, '\n')
    end
end

# Report the nIXS Bessel moments as a sanity check.
P3d = rw.P["3d"]
norm = radial_integral(P3d, P3d, rw.r, 0; kind = :power, weight = :reduced)
Rj = Dict(k => radial_integral(P3d, P3d, rw.r, k; kind = :bessel, q = 4.5, weight = :reduced)
          for k in (0, 2, 4))
println("wrote $(outpath)  ($(length(rw.r)) mesh points)")
println("  ∫P_3d² dr = $(round(norm; digits = 5))")
println("  Rj0,Rj2,Rj4 (q=4.5/a₀) = $(round(Rj[0]; digits=4)), " *
        "$(round(Rj[2]; digits=4)), $(round(Rj[4]; digits=4))")
