# GroupElement, ComplexIR, IRrep, PointGroup; closure, mult-table,
# conjugacy classes, Burnside-Dixon character computation,
# Frobenius-Schur folding, Mulliken-label fingerprinting, ρ_γ bootstrap.

# ─── Types ──────────────────────────────────────────────────────────

"""
    GroupElement

A single symmetry operation of a point group: a proper or improper rotation
stored as its `3×3` Cartesian `matrix` (an `SMatrix`), together with a
Schoenflies `tag` (e.g. `:C3z`, `:σv`, `:i`). Two elements compare equal when
their matrices agree to a small tolerance.
"""
struct GroupElement
    matrix::SMatrix{3,3,Float64,9}
    tag::Symbol
end

# Approximate equality for elements in Cartesian frame.
const _ELEMENT_ATOL = 1e-10

function _isapprox(a::SMatrix{3,3,Float64,9}, b::SMatrix{3,3,Float64,9})
    @inbounds for k in 1:9
        abs(a[k] - b[k]) > _ELEMENT_ATOL && return false
    end
    return true
end

Base.:(==)(a::GroupElement, b::GroupElement) = _isapprox(a.matrix, b.matrix)

# Absolutely irreducible (over C) representation.
struct ComplexIR
    id::Symbol
    dim::Int
    characters::Vector{ComplexF64}        # one per conjugacy class
    matrices::Vector{Matrix{ComplexF64}}  # ρ_γ(g) per element g
    fs_indicator::Int                     # +1, 0, -1
end

# Displayed Mulliken irrep (real-type labelling).
#
# `provenance` distinguishes labels from a curated reference table
# (`:reference`, suitable for production APIs whose stability matters)
# from labels generated by the structural auto-namer (`:computed_auto`,
# suitable for teaching/exploration but not production). The two flow
# through the same internal pipeline; only public-API gating uses the
# distinction.
"""
    IRrep

A real-type irreducible representation of a `PointGroup`, displayed with its
Mulliken `label` (e.g. `:A1g`, `:T2g`). Fields: `label`, `real_dim` (dimension
over ℝ), `complex_constituents` (the absolutely-irreducible constituents over
ℂ), `characters` (one per conjugacy class), and `provenance` (`:reference` for
curated-table labels, `:computed_auto` for auto-generated ones).
"""
struct IRrep
    label::Symbol
    real_dim::Int
    complex_constituents::Vector{Symbol}
    characters::Vector{ComplexF64}
    provenance::Symbol      # :reference or :computed_auto
end

"""
    PointGroup

A finite crystallographic or molecular point group in its Cartesian
representation, constructed with `pointgroup(name)`. Carries the group `name`
and `setting`, the `generators` and full `elements` list, the multiplication
table and `inverses`, the conjugacy `classes`, and both the complex and real
(`IRrep`) irreducible representations. Consumed by `subduce`, `project`,
`character_table`, and the `Akm` crystal-field expansions.
"""
mutable struct PointGroup
    name::Symbol
    setting::Symbol
    generators::Vector{GroupElement}
    elements::Vector{GroupElement}
    multable::Matrix{Int}
    inverses::Vector{Int}
    classes::Vector{Vector{Int}}
    class_reps::Vector{Int}
    complex_irreps::Dict{Symbol, ComplexIR}
    irreps::Vector{IRrep}
end

Base.show(io::IO, G::PointGroup) =
    print(io, "PointGroup(", G.name,
          G.setting === :default ? "" : ", setting=$(G.setting)",
          ", |G|=", length(G.elements),
          ", ", length(G.irreps), " IRs)")

# ─── BFS closure from generators ─────────────────────────────────────

# Identity element with a tagged label.
const _IDENTITY = GroupElement(
    SMatrix{3,3,Float64}(1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0),
    :E,
)

function _find_index(elems::Vector{GroupElement}, M::SMatrix{3,3,Float64,9})
    @inbounds for (k, e) in enumerate(elems)
        _isapprox(e.matrix, M) && return k
    end
    return 0
end

# BFS-close a generator list. Caps at `cap` to defend against runaway
# from a wrong generator (crystallographic max is |Oh|=48; |Ih|=120).
function _bfs_close(gens::Vector{GroupElement}; cap::Int=512)
    elems = GroupElement[_IDENTITY]
    for g in gens
        _find_index(elems, g.matrix) == 0 && push!(elems, g)
    end
    frontier = collect(2:length(elems))
    while !isempty(frontier)
        new_frontier = Int[]
        for i in frontier, j in 1:length(elems)
            P = elems[i].matrix * elems[j].matrix
            if _find_index(elems, P) == 0
                tag = Symbol(elems[i].tag, "·", elems[j].tag)
                push!(elems, GroupElement(P, tag))
                push!(new_frontier, length(elems))
                length(elems) > cap && error(
                    "BFS closure exceeded cap=$cap; bad generator?")
            end
            # Also check left-products of new with existing.
            P2 = elems[j].matrix * elems[i].matrix
            if _find_index(elems, P2) == 0
                tag = Symbol(elems[j].tag, "·", elems[i].tag)
                push!(elems, GroupElement(P2, tag))
                push!(new_frontier, length(elems))
                length(elems) > cap && error(
                    "BFS closure exceeded cap=$cap; bad generator?")
            end
        end
        frontier = new_frontier
    end
    return elems
end

# ─── Multiplication table, inverses, classes ────────────────────────

function _build_multable(elems::Vector{GroupElement})
    n = length(elems)
    M = Matrix{Int}(undef, n, n)
    for i in 1:n, j in 1:n
        idx = _find_index(elems, elems[i].matrix * elems[j].matrix)
        idx == 0 && error("multiplication-table closure failure: e_$i·e_$j missing")
        M[i, j] = idx
    end
    return M
end

function _build_inverses(multable::Matrix{Int})
    n = size(multable, 1)
    inv = Vector{Int}(undef, n)
    e_idx = 1   # identity is at position 1 by construction
    for i in 1:n
        j = findfirst(==(e_idx), multable[i, :])
        j === nothing && error("element $i has no inverse")
        inv[i] = j
    end
    return inv
end

function _build_classes(multable::Matrix{Int}, inverses::Vector{Int})
    n = size(multable, 1)
    seen = falses(n)
    classes = Vector{Vector{Int}}()
    for i in 1:n
        seen[i] && continue
        orbit = Int[]
        for g in 1:n
            # g · i · g^{-1}
            j = multable[multable[g, i], inverses[g]]
            j ∈ orbit || push!(orbit, j)
        end
        sort!(orbit)
        for j in orbit
            seen[j] = true
        end
        push!(classes, orbit)
    end
    return classes
end

# ─── Regular representation and class operators ──────────────────────

function _regular_rep(multable::Matrix{Int})
    n = size(multable, 1)
    L = [zeros(ComplexF64, n, n) for _ in 1:n]
    # L(g) e_h = e_{gh}: L(g)[gh, h] = 1.
    for g in 1:n, h in 1:n
        L[g][multable[g, h], h] = 1.0
    end
    return L
end

function _class_operators(L::Vector{Matrix{ComplexF64}}, classes::Vector{Vector{Int}})
    Z = [zeros(ComplexF64, size(L[1])) for _ in 1:length(classes)]
    for (k, C) in enumerate(classes), g in C
        Z[k] .+= L[g]
    end
    return Z
end

# ─── Burnside / class-operator algorithm ─────────────────────────────

# Group eigenvalues into common-eigenspace blocks. Two eigenvalues are
# "the same" if |λ_i - λ_j| < atol.
function _block_eigenvalues(λ::Vector{ComplexF64}; atol::Float64=1e-7)
    n = length(λ)
    assigned = falses(n)
    blocks = Vector{Vector{Int}}()
    for i in 1:n
        assigned[i] && continue
        push!(blocks, Int[])
        for j in i:n
            !assigned[j] && abs(λ[i] - λ[j]) < atol || continue
            push!(blocks[end], j)
            assigned[j] = true
        end
    end
    return blocks
end

# Compute complex character table by simultaneous diagonalisation of
# class operators in the regular representation. Returns a vector of
# (dim, characters) pairs in BFS-discovery order (each `characters` row
# is one entry per conjugacy class).
function _burnside_characters(Z::Vector{Matrix{ComplexF64}}, classes::Vector{Vector{Int}}, ngroup::Int)
    r = length(Z)
    # Pick a generic Hermitian linear combination. Hermitian to ensure
    # eigen() returns orthogonal eigenvectors despite numerical noise.
    rng = Random.MersenneTwister(42)
    coefs = randn(rng, r)
    Zsum = zeros(ComplexF64, size(Z[1]))
    for k in 1:r
        Zsum .+= coefs[k] .* Z[k]
    end
    H = (Zsum + Zsum') / 2
    F = eigen(Hermitian(H))
    blocks = _block_eigenvalues(ComplexF64.(F.values))

    # Each block, in principle, corresponds to one isotypic component
    # of dim d_γ². Refine if needed (multiple isotypics fused by a
    # numerically-degenerate eigenvalue).
    irreps_data = Vector{Tuple{Int, Vector{ComplexF64}, Matrix{ComplexF64}}}()
    for blk in blocks
        Vblk = F.vectors[:, blk]   # block subspace
        sub_blocks = _refine_block(Vblk, Z, ngroup)
        for sb in sub_blocks
            push!(irreps_data, sb)
        end
    end

    # Pull out (dim, characters) per IR; deduplicate identical rows
    # (the regular rep contains d_γ copies of each γ → multiple
    # eigenspaces correspond to the same IR; merge).
    seen_chars = Vector{Tuple{Int, Vector{ComplexF64}}}()
    for (d, χ, _Vproj) in irreps_data
        any(s -> s[1] == d && all(abs.(s[2] .- χ) .< 1e-6), seen_chars) && continue
        push!(seen_chars, (d, χ))
    end
    # Verify Σ d² = |G|
    if sum(d^2 for (d, _) in seen_chars) != ngroup
        error("character-recovery dimension sum = $(sum(d^2 for (d, _) in seen_chars)), expected $ngroup")
    end
    # Verify orthogonality across complex IRs.
    for i in eachindex(seen_chars), j in eachindex(seen_chars)
        di, χi = seen_chars[i]
        dj, χj = seen_chars[j]
        s = ComplexF64(0)
        for k in 1:length(classes)
            s += conj(χi[k]) * χj[k] * length(classes[k])
        end
        target = i == j ? ComplexF64(ngroup) : ComplexF64(0)
        abs(s - target) < 1e-6 || error(
            "character orthogonality failed: ⟨χ_$i, χ_$j⟩ = $s (target $target)")
    end
    return seen_chars
end

# Refine a block (eigenspace of the random combo) into single isotypic
# components if degenerate. Returns list of (dim, characters, _).
function _refine_block(Vblk::AbstractMatrix, Z::Vector{Matrix{ComplexF64}}, ngroup::Int)
    nblk = size(Vblk, 2)
    # Heuristic d_γ from block size: regular rep has Γ-isotypic of dim
    # d_γ² for each absolutely irreducible γ. If √n_blk is integer, the
    # block is one IR's isotypic.
    d_guess = round(Int, sqrt(nblk))
    if d_guess^2 == nblk
        # Single isotypic. Compute character row via class-operator traces.
        χ = ComplexF64[(tr(Vblk' * Z[k] * Vblk) / nblk) * d_guess /
                       length(_class_size_lookup(Z, k))
                       for k in 1:length(Z)]
        return [(d_guess, χ, ComplexF64.(Vblk))]
    end
    # Otherwise, refine: simultaneously diagonalise all Z_k projected to
    # this block.
    sub_blocks = _simultaneous_diagonalise(Vblk, Z)
    out = Vector{Tuple{Int, Vector{ComplexF64}, Matrix{ComplexF64}}}()
    for V_iso in sub_blocks
        n_iso = size(V_iso, 2)
        d = round(Int, sqrt(n_iso))
        d^2 == n_iso || error("refinement produced non-square isotypic dim $n_iso")
        χ = ComplexF64[(tr(V_iso' * Z[k] * V_iso) / n_iso) * d /
                       length(_class_size_lookup(Z, k)) for k in 1:length(Z)]
        push!(out, (d, χ, ComplexF64.(V_iso)))
    end
    return out
end

# Class-size lookup via Z[k]: each Z_k is a sum of |C_k| permutation
# matrices, so trace(Z_k) = 0 in general. We pass class info externally
# via a closure binding; here, |C_k| equals the column-sum of any column
# of Z_k since each permutation contributes exactly 1 per column.
function _class_size_lookup(Z::Vector{Matrix{ComplexF64}}, k::Int)
    # |C_k| = sum of any column of Z_k (real)
    n = size(Z[k], 1)
    s = real(sum(view(Z[k], :, 1)))
    sz = round(Int, s)
    return 1:sz   # only length is used
end

# Simultaneous diagonalisation of {Z_k} restricted to a degenerate block.
# Returns list of column-spans, one per common-eigenspace.
function _simultaneous_diagonalise(Vblk::AbstractMatrix, Z::Vector{Matrix{ComplexF64}};
                                    atol::Float64=1e-7)
    blocks = [collect(1:size(Vblk, 2))]
    Vcurrent = ComplexF64.(Vblk)
    for k in 1:length(Z)
        Zproj = Vcurrent' * Z[k] * Vcurrent
        Zh = (Zproj + Zproj') / 2 + 1im * ((Zproj - Zproj') / 2im)
        F = eigen(Zh)
        new_blocks = Vector{Vector{Int}}()
        for blk in blocks
            sub_λ = F.values[blk]
            sub_groups = _block_eigenvalues(ComplexF64.(sub_λ); atol)
            for sg in sub_groups
                push!(new_blocks, blk[sg])
            end
        end
        # Apply rotation
        Vcurrent = Vcurrent * F.vectors
        blocks = new_blocks
        # Stop early if every block is square in d (single isotypic)
        all(b -> isinteger(sqrt(length(b))), blocks) && break
    end
    return [Vcurrent[:, b] for b in blocks]
end

# ─── Frobenius-Schur folding (Mulliken display labels) ───────────────

function _frobenius_schur(characters::Vector{ComplexF64},
                          multable::Matrix{Int}, classes::Vector{Vector{Int}})
    # ν = (1/|G|) Σ_g χ(g²)
    n = size(multable, 1)
    elem_to_class = Vector{Int}(undef, n)
    for (k, C) in enumerate(classes), g in C
        elem_to_class[g] = k
    end
    ν = ComplexF64(0)
    for g in 1:n
        g2 = multable[g, g]
        ν += characters[elem_to_class[g2]]
    end
    ν /= n
    # Round to nearest integer in {-1, 0, +1}; assert close.
    νr = real(ν)
    abs(imag(ν)) < 1e-6 || error("FS indicator imaginary part nonzero: $ν")
    for v in (-1, 0, 1)
        abs(νr - v) < 1e-4 && return v
    end
    error("FS indicator $νr not in {-1, 0, +1}")
end

# Pair complex-type (ν=0) IRs with their conjugates, returning a vector
# of IR groups: each group is a list of complex-IR indices (1 entry for
# real-type, 2 for folded complex pair).
function _fold_complex_irreps(complex_chars::Vector{Tuple{Int, Vector{ComplexF64}}},
                              fs_indicators::Vector{Int})
    n = length(complex_chars)
    paired = falses(n)
    folds = Vector{Vector{Int}}()
    for i in 1:n
        paired[i] && continue
        if fs_indicators[i] != 0
            push!(folds, [i])
            paired[i] = true
        else
            # find its conjugate: same dim, characters = conj(characters[i])
            di, χi = complex_chars[i]
            j = findfirst(k -> !paired[k] && k != i &&
                          complex_chars[k][1] == di &&
                          all(abs.(complex_chars[k][2] .- conj.(χi)) .< 1e-6),
                          1:n)
            j === nothing && error(
                "complex-type IR #$i has no conjugate partner; group has " *
                "FS-classification bug or quaternionic IR (not supported)")
            push!(folds, [i, j])
            paired[i] = true
            paired[j] = true
        end
    end
    return folds
end

# ─── Mulliken-label assignment (structural auto-namer) ───────────────

# Teaching/fallback structural auto-namer for groups absent from the
# reference table layer. Family by dim (1D→A, 2D→E, 3D→T, 4D→G, 5D→H),
# parity g/u suffix when the group contains -I, integer counter to
# disambiguate (so two 3D-g IRs become :T1g and :T2g, but in BFS
# discovery order — not guaranteed to match any published convention).
# IRrep.provenance = :computed_auto for these.
function _assign_labels(folds::Vector{Vector{Int}},
                        complex_chars::Vector{Tuple{Int, Vector{ComplexF64}}},
                        classes::Vector{Vector{Int}},
                        elements::Vector{GroupElement})
    inv_class = _inversion_class(classes, elements)
    has_inv = inv_class > 0
    labels = Vector{Symbol}(undef, length(folds))
    counters = Dict{Char, Int}()
    counters_g = Dict{Char, Int}()
    counters_u = Dict{Char, Int}()
    for (k, fold) in enumerate(folds)
        # real-displayed dim
        if length(fold) == 1
            d, χ = complex_chars[fold[1]]
            real_dim = d
        else
            d, χ = complex_chars[fold[1]]
            real_dim = 2 * d
            χ = χ + complex_chars[fold[2]][2]
        end
        family = real_dim == 1 ? 'A' :
                 real_dim == 2 ? 'E' :
                 real_dim == 3 ? 'T' :
                 real_dim == 4 ? 'G' :
                 real_dim == 5 ? 'H' : '?'
        if has_inv
            parity = real(χ[inv_class]) > 0 ? 'g' : 'u'
            tab = parity == 'g' ? counters_g : counters_u
            tab[family] = get(tab, family, 0) + 1
            n = tab[family]
            labels[k] = Symbol(family, n, parity)
        else
            counters[family] = get(counters, family, 0) + 1
            n = counters[family]
            labels[k] = Symbol(family, n)
        end
    end
    return labels
end

function _inversion_class(classes::Vector{Vector{Int}}, elements::Vector{GroupElement})
    inv_idx = findfirst(e -> _isapprox(e.matrix,
                                       SMatrix{3,3,Float64}(-1.0, 0.0, 0.0,
                                                            0.0, -1.0, 0.0,
                                                            0.0, 0.0, -1.0)),
                        elements)
    inv_idx === nothing && return 0
    for (k, C) in enumerate(classes)
        inv_idx ∈ C && return k
    end
    return 0
end

# ─── ρ_γ matrix bootstrap (smallest-ℓ-with-mult-1 rule) ──────────────

# For a complex IR γ with d_γ > 1, find the smallest ℓ where the
# multiplicity of γ in D^ℓ↓G equals 1. The γ-isotypic of D^ℓ then has
# dimension exactly d_γ; we extract ρ_γ matrices by acting D^ℓ(g) on
# that subspace expressed in a deterministic tesseral basis.
#
# For d_γ = 1, ρ_γ(g) is the 1×1 matrix [χ_γ(g)] directly.

function _bootstrap_rho_matrices!(G::PointGroup, complex_chars::Vector{Tuple{Int, Vector{ComplexF64}}},
                                  fs_indicators::Vector{Int})
    n_elems = length(G.elements)
    elem_to_class = Vector{Int}(undef, n_elems)
    for (k, C) in enumerate(G.classes), g in C
        elem_to_class[g] = k
    end
    n_irreps = length(complex_chars)
    rhos = Vector{Union{Nothing, Vector{Matrix{ComplexF64}}}}(nothing, n_irreps)
    pending = Int[]   # IRs deferred for parity-twin fallback
    for (γ_idx, (d_γ, χ_γ)) in enumerate(complex_chars)
        if d_γ == 1
            # 1×1 matrices = scalar character per element.
            rhos[γ_idx] = [reshape(ComplexF64[χ_γ[elem_to_class[g]]], 1, 1)
                           for g in 1:n_elems]
            continue
        end
        # d_γ > 1: try smallest D^ℓ where mult(γ, D^ℓ) == 1.
        try
            rhos[γ_idx] = _bootstrap_rho_from_Dl(G, χ_γ, d_γ, elem_to_class)
        catch e
            isa(e, ErrorException) || rethrow(e)
            occursin("no ℓ ≤", e.msg) || rethrow(e)
            push!(pending, γ_idx)
        end
    end
    # Parity-twin fallback: for centrosymmetric groups, every irrep γ
    # has a partner γ' with χ_γ(g) = det(R(g))·χ_{γ'}(g). If γ' was
    # bootstrapped successfully, ρ_γ(g) = det(R(g))·ρ_{γ'}(g).
    if !isempty(pending)
        signs = Float64[det(G.elements[g].matrix) for g in 1:n_elems]
        for γ_idx in pending
            d_γ, χ_γ = complex_chars[γ_idx]
            partner = nothing
            for j in 1:n_irreps
                j == γ_idx && continue
                rhos[j] === nothing && continue
                d_j, χ_j = complex_chars[j]
                d_j == d_γ || continue
                # check χ_γ(g) = ε(g) χ_j(g) per class
                ok = true
                for (k, C) in enumerate(G.classes)
                    s_class = signs[C[1]]    # ε is class-constant
                    abs(χ_γ[k] - s_class * χ_j[k]) < 1e-6 || (ok = false; break)
                end
                ok || continue
                partner = j
                break
            end
            partner === nothing && error(
                "ρ_γ bootstrap: irrep #$γ_idx (d=$d_γ) has no mult-1 occurrence " *
                "in D^ℓ for ℓ ≤ 8 and no parity-twin partner found. " *
                "Consider extending data.jl with explicit ρ matrices for this irrep.")
            ρ_partner = rhos[partner]::Vector{Matrix{ComplexF64}}
            rhos[γ_idx] = [signs[g] * ρ_partner[g] for g in 1:n_elems]
        end
    end
    return Vector{Vector{Matrix{ComplexF64}}}(rhos)
end

function _bootstrap_rho_from_Dl(G::PointGroup, χ_γ::Vector{ComplexF64}, d_γ::Int,
                                elem_to_class::Vector{Int}; ℓ_max::Int=8)
    n_elems = length(G.elements)
    ngroup = n_elems
    for ℓ in 1:ℓ_max
        # Build D^ℓ(g) for every g.
        Dl = [_wignerd_matrix(G.elements[g].matrix, ℓ) for g in 1:n_elems]
        # Multiplicity of γ in D^ℓ via character inner product.
        χ_Dl = ComplexF64[tr(Dl[g]) for g in 1:n_elems]
        m_γ = ComplexF64(0)
        for g in 1:n_elems
            m_γ += conj(χ_γ[elem_to_class[g]]) * χ_Dl[g]
        end
        m_γ /= ngroup
        m_int = round(Int, real(m_γ))
        abs(m_γ - m_int) < 1e-6 || continue
        m_int == 1 || continue
        # γ-isotypic projector P_γ on V_ℓ.
        dim_ℓ = 2ℓ + 1
        P_γ = zeros(ComplexF64, dim_ℓ, dim_ℓ)
        for g in 1:n_elems
            P_γ .+= conj(χ_γ[elem_to_class[g]]) * Dl[g]
        end
        P_γ .*= d_γ / ngroup
        # γ-isotypic subspace: image of P_γ. SVD for a deterministic
        # orthonormal basis; pick top-d_γ singular vectors.
        F = svd(P_γ)
        rank_check = count(s -> s > 1e-7, F.S)
        rank_check == d_γ || error(
            "γ-isotypic of D^$ℓ has rank $rank_check, expected $d_γ")
        U_γ = F.U[:, 1:d_γ]   # orthonormal basis of γ-isotypic
        # ρ_γ(g) = action of D^ℓ(g) restricted to span(U_γ), in the
        # U_γ basis: ρ_γ(g) = U_γ^† D^ℓ(g) U_γ.
        ρ = [U_γ' * Dl[g] * U_γ for g in 1:n_elems]
        # Closure verification: ρ(g_i) ρ(g_j) = ρ(multable[i,j]).
        for i in 1:n_elems, j in 1:n_elems
            target = ρ[G.multable[i, j]]
            err = opnorm(ρ[i] * ρ[j] - target)
            err > 1e-7 && error(
                "ρ_γ closure failed at (g_$i, g_$j): err=$err (ℓ=$ℓ, d_γ=$d_γ)")
        end
        # Character recovery
        for g in 1:n_elems
            err = abs(tr(ρ[g]) - χ_γ[elem_to_class[g]])
            err > 1e-7 && error(
                "ρ_γ character recovery failed at g=$g: err=$err")
        end
        return ρ
    end
    error("ρ_γ bootstrap: no ℓ ≤ $ℓ_max gave multiplicity 1 for d_γ=$d_γ irrep " *
          "(likely a high-multiplicity-only irrep; not supported by the bootstrap alone)")
end

# ─── Top-level construction ──────────────────────────────────────────

function _construct_pointgroup(name::Symbol, setting::Symbol,
                                gens_data::Vector{<:Tuple})
    generators = [GroupElement(SMatrix{3,3,Float64,9}(M), tag)
                  for (M, tag) in gens_data]
    # Verify Cartesian orthogonality of every generator.
    for g in generators
        norm(g.matrix' * g.matrix - I) < 1e-10 || error(
            "generator $(g.tag) is not orthogonal (R^T R - I norm = " *
            "$(norm(g.matrix' * g.matrix - I)))")
    end
    elements   = _bfs_close(generators)
    multable   = _build_multable(elements)
    inverses   = _build_inverses(multable)
    classes    = _build_classes(multable, inverses)
    class_reps = [minimum(C) for C in classes]
    # Verify Cartesian orthogonality + determinant for every closed element.
    for e in elements
        norm(e.matrix' * e.matrix - I) < 1e-9 || error(
            "closed element $(e.tag) not orthogonal")
    end

    # Burnside character table (complex IRs).
    L = _regular_rep(multable)
    Z = _class_operators(L, classes)
    complex_chars = _burnside_characters(Z, classes, length(elements))

    # Frobenius-Schur folding.
    fs_indicators = [_frobenius_schur(χ, multable, classes)
                     for (_, χ) in complex_chars]
    folds = _fold_complex_irreps(complex_chars, fs_indicators)

    # ρ_γ matrices via bootstrap.
    G_partial = PointGroup(name, setting, generators, elements, multable,
                           inverses, classes, class_reps,
                           Dict{Symbol, ComplexIR}(), IRrep[])
    rhos = _bootstrap_rho_matrices!(G_partial, complex_chars, fs_indicators)

    # Build ComplexIR registry, keyed by id :γ_1 .. :γ_n.
    complex_irreps = Dict{Symbol, ComplexIR}()
    cir_ids = Vector{Symbol}(undef, length(complex_chars))
    for k in eachindex(complex_chars)
        d, χ = complex_chars[k]
        id = Symbol("γ_", k)
        complex_irreps[id] = ComplexIR(id, d, χ, rhos[k], fs_indicators[k])
        cir_ids[k] = id
    end

    # Two-layer label assignment:
    #   - Production layer: match against the curated reference table
    #     (`reference_tables.jl`). On match, IRrep.provenance = :reference
    #     and the Burnside-computed character table is cross-validated
    #     against the reference (any mismatch raises).
    #   - Teaching/fallback layer: structural auto-naming. IRrep.provenance
    #     = :computed_auto. Public APIs that require canonical labels
    #     (e.g. `expand_clm`) refuse these unless explicitly opted in.
    ref_match = _assign_reference_labels(name, folds, complex_chars, classes,
                                          elements, multable;
                                          generators=generators)
    ref_labels, class_perm = ref_match
    use_reference = ref_labels !== nothing
    labels = use_reference ? ref_labels :
             _assign_labels(folds, complex_chars, classes, elements)
    provenance = use_reference ? :reference : :computed_auto

    irreps = Vector{IRrep}(undef, length(folds))
    for (k, fold) in enumerate(folds)
        constituents = Symbol[cir_ids[i] for i in fold]
        χ_disp = sum(complex_chars[i][2] for i in fold)
        d_real = length(fold) == 1 ? complex_chars[fold[1]][1] : 2 * complex_chars[fold[1]][1]
        irreps[k] = IRrep(labels[k], d_real, constituents, χ_disp, provenance)
    end

    # Cross-validate the Burnside-computed table against the reference.
    if use_reference
        _validate_against_reference(name, labels, complex_chars, folds, class_perm)
    end

    # Sort by reference-table IR order if available; otherwise
    # (real_dim asc, label) for deterministic auto-named ordering.
    if use_reference
        ref_order = REFERENCE_CHARACTER_TABLES[name].irreps
        order = sortperm(irreps;
                         by = ir -> something(findfirst(==(ir.label), ref_order),
                                              length(ref_order) + 1))
    else
        order = sortperm(irreps; by = ir -> (ir.real_dim, String(ir.label)))
    end
    irreps_sorted = irreps[order]

    G_partial.complex_irreps = complex_irreps
    G_partial.irreps = irreps_sorted

    return G_partial
end
